### ISSUE TITLE
let's collaborate on hosting these endpoints

### ISSUE THREAD

**Issue by derhuerst** [Transportflow/HafasRestEndpoint#1]
Hey!

I run some public `hafas-rest-api`-based endpoints at [`transport.rest`](https://transport.rest), because I want this data to be (more) easily accessible; This fits your @Transportflow motto ("Making public transport more accessible with open source").

We don't need to have the burden of having two entirely separate endpoints, let's collaborate! I just created public-transport/transport.rest#2 to find a sustainable collaborative setup. You're welcome to give your opinions!

**Comment by Adwirawien** [comment]
Sounds pretty awesome!
I could definitely run some instances on my servers.
Just tell me which ones you have in mind and if you have docker images for them.

**Comment by derhuerst** [comment]
Cool! I will mention you in public-transport/transport.rest#2 once we've settled the general setup.

**Comment by Adwirawien** [comment]
Alright, looking forward to that! 🚋🚍🚀
